package model;
// Generated Sep 11, 2019 5:56:11 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.OneToMany;

/**
 * Employees generated by hbm2java
 */
public class Employees  implements java.io.Serializable {


     private int empNo;
     private Date birthDate;
     private String firstName;
     private String lastName;
     private String gender;
     private Date hireDate;
     private Set titleses = new HashSet(0);
     private Set salarieses = new HashSet(0);
     @OneToMany(mappedBy="employees")
     private Set deptEmps = new HashSet(0);
     private Set deptManagers = new HashSet(0);

    public Employees() {
    }

	
    public Employees(int empNo, Date birthDate, String firstName, String lastName, String gender, Date hireDate) {
        this.empNo = empNo;
        this.birthDate = birthDate;
        this.firstName = firstName;
        this.lastName = lastName;
        this.gender = gender;
        this.hireDate = hireDate;
    }
    public Employees(int empNo, Date birthDate, String firstName, String lastName, String gender, Date hireDate, Set titleses, Set salarieses, Set deptEmps, Set deptManagers) {
       this.empNo = empNo;
       this.birthDate = birthDate;
       this.firstName = firstName;
       this.lastName = lastName;
       this.gender = gender;
       this.hireDate = hireDate;
       this.titleses = titleses;
       this.salarieses = salarieses;
       this.deptEmps = deptEmps;
       this.deptManagers = deptManagers;
    }
   
    public int getEmpNo() {
        return this.empNo;
    }
    
    public void setEmpNo(int empNo) {
        this.empNo = empNo;
    }
    public Date getBirthDate() {
        return this.birthDate;
    }
    
    public void setBirthDate(Date birthDate) {
        this.birthDate = birthDate;
    }
    public String getFirstName() {
        return this.firstName;
    }
    
    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }
    public String getLastName() {
        return this.lastName;
    }
    
    public void setLastName(String lastName) {
        this.lastName = lastName;
    }
    public String getGender() {
        return this.gender;
    }
    
    public void setGender(String gender) {
        this.gender = gender;
    }
    public Date getHireDate() {
        return this.hireDate;
    }
    
    public void setHireDate(Date hireDate) {
        this.hireDate = hireDate;
    }
    public Set getTitleses() {
        return this.titleses;
    }
    
    public void setTitleses(Set titleses) {
        this.titleses = titleses;
    }
    public Set getSalarieses() {
        return this.salarieses;
    }
    
    public void setSalarieses(Set salarieses) {
        this.salarieses = salarieses;
    }
    public Set getDeptEmps() {
        return this.deptEmps;
    }
    
    public void setDeptEmps(Set deptEmps) {
        this.deptEmps = deptEmps;
    }
    public Set getDeptManagers() {
        return this.deptManagers;
    }
    
    public void setDeptManagers(Set deptManagers) {
        this.deptManagers = deptManagers;
    }




}


